### PR TITLE
Modifying projection and colorscheme for plot.py

### PR DESCRIPTION
**Pull request by Lazzerac**

### CODE REVIEW

**Comment by eheien** [comment]
It looks like there's some mixing of files here.  It appears you have modified the files in the normal repository, but you have also created a subfolder in the cig_backend repository named cig_backend (so some files are in cig_backend:cig_backend/map/ rather than cig_backend:map/).  Could you put everything in the normal folders?  Thanks!

**Comment by Lazzerac** [comment]
Fixed it - everything should be in the correct place now.

**Comment by eheien** [comment]
I can't seem to get this to work - it gets stuck on one of the pscoast commands for an indeterminate amount of time.  Also, I think the location for data.nc and data_i.nc isn't referenced properly in the script - if I run plot.py in the map_plot directory it can't find these data files.  Could you look into this?  Thanks!

**Comment by Lazzerac** [comment]
What version of GMT are you using? 

I'm able to run (in the directory above map_plot) ploy.py with a command like this:
map_plot/plot.py hit_database/hit_database ip_database/ip_lookup_db ./ all `date --date="3 month ago" +'%s'`

I'll edit the file location in plot.py - will the cron job look the same as the command above?

**Comment by eheien** [comment]
It's GMT 4.5.11 - do your changes require GMT 5?  The cron command is similar to the one you wrote except it's executed in the cig_backend:map/map_plot directory rather than the cig_backend:map directory.  This is why there is sys.path.append("../..") in plot.py - otherwise it won't find cig_codes.py in the base directory.

**Comment by Lazzerac** [comment]
Yes - upgrading GMT gave the best results so far. It seems as though the GMT commands only look in the directory in which they are exectued in; moving data.nc and data_i.nc would be a quick fix.

**Comment by eheien** [comment]
I just asked the admin to upgrade to GMT 5, I'll try again when that's installed and let you know how it works.

**Comment by eheien** [comment]
Just FYI, we're still working on getting this running.  There are issues installing the latest version of GMT and gshhg.

**Comment by Lazzerac** [comment]
Building from source was the only successful install I had which produced the correct images. 

http://gmt.soest.hawaii.edu/projects/gmt/wiki/BuildingGMT

**Comment by eheien** [comment]
Working fine now, feel free to take a look at any software page to see the results.

**Pull request merged**
